[package]
name = "day_0"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "advent_of_code"
path = "main.rs"

[dependencies]
tokio = {version = "1.41", features = ["full"]}
anyhow = "1.0"
once_cell = "1.20.2"
regex = "1.11.1"
image = "0.25.5"
